M48
; DRILL file {KiCad (7.0.0)} date Tue Aug  8 03:57:21 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.1378
%
G90
G05
T1
X5.02Y-3.82
X5.03Y-3.716
T2
X5.2398Y-3.8
X5.2398Y-3.9
X5.35Y-3.8
X5.35Y-3.9
T3
X4.84Y-3.7494
X4.84Y-3.8494
X4.84Y-3.9494
T4
X4.15Y-3.85
T0
M30
